#服务的消费方...

server:
  port: 8080
spring:
  application:
    name: service-consumer
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
    fetch-registry: true #拉取eureka服务信息
    registry-fetch-interval-seconds: 5 #每隔5秒钟,从eureka容器拉取已经注册的信息